name: Publication on NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      INPUT_TOKEN: ''

    steps:
    - uses: actions/checkout@v1
    - name: Build custom-element-ts
      run: |
        npm install
        npm run build
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - name: Build @custom-element-ts/three
      run: |
        cd packages/three
        npm install
        npm run build
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: './packages/three/package.json'
        access: public
